DROP TYPE IF EXISTS exp_level;
CREATE TYPE exp_level AS ENUM (
  'entry',
  'mid',
  'senior'
);

DROP TYPE IF EXISTS job_type;
CREATE TYPE job_type AS ENUM (
  'full-time',
  'part-time',
  'internship',
  'temporary',
  'contract'
);

CREATE TABLE "jobs" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INTEGER REFERENCES "user"(id) NOT NULL,
  "description" TEXT NOT NULL,
  "reqs" TEXT NOT NULL,
  "salary" INTEGER,
  "exp_level" exp_level,
  "job_type" job_type,
  "expiry" TEXT NOT NULL DEFAULT '30 days',
  "created_on" TIMESTAMP NOT NULL DEFAULT NOW(),
  "has_expired" BOOLEAN DEFAULT FALSE,
  "contact" TEXT NOT NULL
);