CREATE TABLE "user_resume" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER REFERENCES "user"(id) NOT NULL,
    "resume" BYTEA NOT NULL,
    "original_name" TEXT NOT NULL
);